/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.dataformat.yaml.YAMLFactory;

//import for XML

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        String jsonString = "{ \"name\":\"John\", \"age\":30, \"city\":\"New York\" }";

        ArgumentParser argsParser = new ArgumentParser(args);
        for (Argument arg : argsParser.getArguments()) {
            System.out.println("Cmd  : " + arg.getCommand());
            System.out.println("param: " + arg.getParameter() + "\n");
        }

        ObjectMapper mapper = new ObjectMapper();
        JsonNode actualObj;

        try {
            actualObj = mapper.readTree(jsonString);
            System.out.println(actualObj.toString());
        } catch (JsonMappingException e) {
            e.printStackTrace();
        } catch (JsonProcessingException e) {
            e.printStackTrace();
        }
    }
}
